### ISSUE TITLE
Strange handling $ONE$TWO

### ISSUE THREAD

**Issue by oturpe** [motdotla/dotenv-expand#103]
Consider the following env file:

```
NO_NO="NO_NO: $NO$NO"
YES_NO="YES_NO: $YES$NO"
YES_YES="YES_YES: $YES$YES"
NO_YES="NO_YES: $NO$YES"
YES_YESS="YES_YESS: $YES$YESS"
```

When NO is not defined and YES and YESS are defined, this results in:

```
NO_NO: 
YES_NO: yes
YES_YES: yesyes
NO_YES: 
YES_YESS:
```

In other words, if ONE and TWO are both defined, $ONE$TWO evaluates to undefined.
This is highly unintuitive.
I expect both variables to be expanded in this case.

As a workaround, ${ONE}${TWO} works as expected.

Version: 10.0.0

This used to work with 5.1.0.

**Comment by motdotla** [comment]
showing failing spec here: https://github.com/motdotla/dotenv-expand/pull/108

**Comment by motdotla** [comment]
fixed here. will go out as part of `v11.0.0` (should be released today or tomorrow) https://github.com/motdotla/dotenv-expand/pull/108

**Comment by oturpe** [comment]
Nice, thanks!
