### ISSUE TITLE
Setting default values if not present in environment

### ISSUE THREAD

**Issue by JoeAlamo** [motdotla/dotenv-expand#11]
Are you able to set default values for the environment variables if they are not present in your environment already, like [in Bash](https://jaduks.livejournal.com/7934.html)?

Or do you recommend we handle this within our code?

**Comment by motdotla** [comment]
I'm not sure I understand.

If setting in `.env` file that will become your default value.

But otherwise, if they are not set there or already on your machine, then yes, you will need your code to conditionally generate a default value.

**Comment by jacobrask** [comment]
The suggestion is to allow the syntax `WEB_PROXY_PORT=${PORT:-3000}`, to set `WEB_PROXY_PORT` to `PORT` if it's already defined, otherwise to `3000`. Does that make sense?

**Comment by vantreeseba** [comment]
This will be fixed by #39
