### ISSUE TITLE
support `'single$quote'` syntax to not expand

### ISSUE THREAD

**Issue by motdotla** [motdotla/dotenv-expand#112]
add feature so that single quote syntax does not expand `$` dollar signs. (this likely requires coordination with [dotenv](https://github.com/motdotla/dotenv)

who needs this? please let me know below.

**Comment by jahdiel** [comment]
This latest release broke my staging environemnt. My .env file has something similar to:
```
HOST="something"
DOMAIN="https://${HOST}"
```
During deployment the dotenv-expand upgraded to the latest release and broke during runtime. The expansion failed, `DOMAIN` ended up with `https://${HOST}` as its value. Not sure if this was a non-backwards compatible release.

**Comment by motdotla** [comment]
@jahdiel what version did you bump up from?

And does your `HOST` value have a `$` dollar sign in it?

**Comment by motdotla** [comment]
@jahdiel nevermind. i see the issue. working on the fix. so sorry about this. in the meantime, you can fix it by changing your dotenv expand code from:

```
var dotenv = require('dotenv')
var dotenvExpand = require('dotenv-expand')
dotenvExpand.expand(dotenv.config())
```

to

```
var dotenv = require('dotenv')
var dotenvExpand = require('dotenv-expand')
dotenvExpand.expand(dotenv.config({ processEnv: {} }))
```

**Comment by motdotla** [comment]
@jahdiel - please install `v11.0.3`. should be fixed. https://github.com/motdotla/dotenv-expand/pull/113

sorry about this one. was a bad one. tests were formatted badly allowing it to sneak in. fixed going forward.

**Comment by motdotla** [comment]
dotenv-expand cannot reliably recognize single quotes. use [dotenvx](https://github.com/dotenvx/dotenvx) to reliably avoid expansion with single quotes.
