### ISSUE TITLE
Possible recursive expansion regression

### ISSUE THREAD

**Issue by kioan000** [motdotla/dotenv-expand#117]
After upgrading from 10.0 to latest 11.0.3

the following .env 

```env
BACKEND_API_HEALTH_CHECK_URL=${MOCK_SERVER_HOST}/ci-health-check
...
MOCK_SERVER_HOST=http://localhost:${MOCK_SERVER_PORT}
MOCK_SERVER_PORT=8090
```

parsed by this script

```ts
expand(dotenv.config({ path: path.resolve(root, '.env') }))

console.log('env', process.env)
```

is not recursively expanded anymore. Now it produces the following result:

```
BACKEND_API_HEALTH_CHECK_URL: 'http://localhost:${MOCK_SERVER_PORT}/ci-health-check',
...
MOCK_SERVER_HOST: 'http://localhost:8090',
MOCK_SERVER_PORT: '8090',

```

**Comment by motdotla** [comment]
looking into this now

**Comment by motdotla** [comment]
effort happening here: https://github.com/motdotla/dotenv-expand/pull/118

**Comment by motdotla** [comment]
something you can do to fix this for yourself right now is to place `BACKEND_API_HEALTH_CHECK_URL` at the end of your .env file. that will expand correctly. https://github.com/motdotla/dotenv-expand/pull/118/commits/67fcfeebaa0524dd7ba83dab3bda9afe9f147fe9#diff-2ab7c3c5008dfeaf54c1692893b6e2677fe5b9afc15935d7c94e515f383deab3R516

**Comment by motdotla** [comment]
update to `11.0.4`. fixed and released there. https://github.com/motdotla/dotenv-expand/blob/master/CHANGELOG.md#1104-2024-02-15
