### ISSUE TITLE
Possible double-recursive expansion regression

### ISSUE THREAD

**Issue by mschoeffmann** [motdotla/dotenv-expand#120]
In addition to #117, there is also a breaking change when referencing a "real" env variable from a .env file.

For example:

Variable (set in docker environment):
`APP_DOMAIN=example.com`

Variable (set in .env):
`BASE_URL=https://${APP_DOMAIN}/api/`

Results in `https://${APP_DOMAIN}/api/`.
In v10 it was correct: `https://example.com/api/`

**Comment by motdotla** [comment]
this appears to be working correctly @mschoeffmann. here's a test demonstrating it. https://github.com/motdotla/dotenv-expand/pull/121/files

what does your dotenv.config and dotenvExpand code look like? keep in mind we removed `ignoreProcessEnv` and replaced it with `processEnv` (https://github.com/motdotla/dotenv-expand/blob/master/CHANGELOG.md#removed). possibly are you using the `processEnv` argument to dotenv.config ?

**Comment by motdotla** [comment]
confirmed issue here: https://github.com/motdotla/dotenv-expand/pull/121 

sorry about this. working on patch.

**Comment by motdotla** [comment]
that one was tricky to track down but is done now. https://github.com/motdotla/dotenv-expand/pull/121/files

install [11.0.5](https://www.npmjs.com/package/dotenv-expand/v/11.0.5) and you should be all set
