### ISSUE TITLE
Inconsistent Behavior with Default Environment Variable Values Using dotenv and dotenv-expand

### ISSUE THREAD

**Issue by GeryDeMerciYanis** [motdotla/dotenv-expand#125]
Hello,

I've encountered an issue regarding **the handling of default environment variable values** when using dotenv in conjunction with dotenv-expand.

The goal is to access an environment variable with the option to fall back to a default value if the variable is not defined. To achieve this, my .env configuration is as follows: `MY_VAR=${MY_VAR:-default-value}`

Upon setting up dotenv and dotenv-expand and subsequently accessing `process.env.MY_VAR`, the output unexpectedly matches the literal string in the .env file: `${MY_VAR:-default-value}`.

However, altering the .env file to use a non-existent variable as the key in the fallback expression: `MY_VAR=${NOT_MY_VAR:-default-value}`
Results in the correct behavior, yielding `default-value` when `process.env.MY_VAR` is accessed.

I've prepared a minimal reproducible example available at: [CodeSandbox - Node.js Playground Forked](https://codesandbox.io/p/devbox/nodejs-playground-forked-wvmjcj?file=%2Fsrc%2Findex.js&workspaceId=5e640ee3-5141-452a-ae61-5a7bedfba6f3).

Environment:

Node.js version: 20.11.0
`dotenv` version: 16.4.5
`dotenv-expand` version: 11.0.6

It appears that dotenv-expand does not process the default value syntax as expected when the variable name is the same as the one being defined. I'm looking forward to any insights or solutions regarding this issue.

Thank you.

**Comment by stvvt** [comment]
I've noticed exactly the same behaviour and proposed https://github.com/motdotla/dotenv-expand/pull/126 to fix it.

**Comment by motdotla** [comment]
thank you for the fix.
