### ISSUE TITLE
[Bug] Can't override existing environment variable

### ISSUE THREAD

**Issue by Dogacel** [motdotla/dotenv-expand#127]
Here is the session:

```bash
export B=2
node

> const dotenv = await import("dotenv");
> const dotenvExpand = await import("dotenv-expand");
undefined
> dotenvExpand.expand({ parsed: dotenv.parse("A=1") }).parsed
{ A: '1' }
> dotenvExpand.expand({ parsed: dotenv.parse("B=1") }).parsed
{ B: '2' }
```

Expected result should be `{ B: '1' }`.

**Comment by motdotla** [comment]
@Dogacel have you tried dotenvx to debug this? it has a fuller solution for this these days and also has built-in debugging.

https://github.com/dotenvx/dotenvx

**Comment by motdotla** [comment]
i've added this to the FAQ:

### How can I override an existing environment variable?

Use [dotenvx](https://github.com/dotenvx/dotenvx) as dotenv-expand does not support this.

dotenv-expand is a separate module (without knowledge of the loading of `process.env` and the `.env` file) and so cannot reliably know what to override.
