### ISSUE TITLE
[question] about docs section: "How can I avoid expanding pre-existing envs"

### ISSUE THREAD

**Issue by gusega** [motdotla/dotenv-expand#132]
Hi all,

I was looking at the docs at the section "How can I avoid expanding pre-existing envs". 

What situation does this section describe?

From my experiments I saw that `dotenvExpand.expand()` expands only what `dotenv.config()` has returned. `dotenv.config()` returns in property `parsed` only what was in the `.env` configuration file.

So it seems to me that passing `{ processEnv: {} }` to `dotenv.config()` in:

```js
const dotenv = require('dotenv')
const dotenvExpand = require('dotenv-expand')

const myEnv = dotenv.config({ processEnv: {} }) // prevent writing to `process.env`

dotenvExpand.expand(myEnv)
```

only prevents adding intermediate (not-expanded) values to `process.env`.

In the end, the program adds expanded `.env` values to `process.env` via `dotenvExpand.expand()`

Please advise.

**Comment by motdotla** [comment]
if you have that need I recommend switching to [dotenvx](https://github.com/dotenvx/dotenvx). it has much more control over this kind of thing.

**Comment by motdotla** [comment]
otherwise, if you don't want to expand then don't use dotenv-expand - just use dotenv.

**Comment by motdotla** [comment]
as of `12.0.0` it is impossible to expand `process.env` values. This was dangerous if one contained a dollar sign - for example a password.
