### ISSUE TITLE
v12 does not support reverse order expansion

### ISSUE THREAD

**Issue by sapphi-red** [motdotla/dotenv-expand#134]
[This test](https://github.com/motdotla/dotenv-expand/pull/118/files#diff-2ab7c3c5008dfeaf54c1692893b6e2677fe5b9afc15935d7c94e515f383deab3R543-R558) for https://github.com/motdotla/dotenv-expand/issues/117 no longer passes with v12. ([reproduction](https://stackblitz.com/edit/node-8sbdzc?file=index.js))

Was this support removed intentionally? or is this a regression?

**Comment by motdotla** [comment]
intentionally. it never should have - it does not work anywhere else - docker-compose, bash, etc. it happened to work because of the nature of dotenv-expand first waiting for dotenv.config() to load to process.env - so essentially all values 'exist' already.

**Comment by sapphi-red** [comment]
Thank you for the quick response.
