### ISSUE TITLE
Support to escape the escape string?

### ISSUE THREAD

**Issue by ddbtrmatic** [motdotla/dotenv-expand#136]
I have the following environment

```
DATABASE: server\instance
```

I would like to use variable substitution

```
DATABASE: server\${INSTANCE}
```

However, dotenv-expand interprets this as an escape sequence for the variable substitution and I'm left with the raw value. How can I use a backslash before a dollar sign and have it interpreted literally?

**Comment by motdotla** [comment]
have you tried using github.com/dotenvx/dotenvx @ddbtrmatic? I recommend switching to that as almost 100% of improvements are going into that. it has expansion built in among other things.
