### ISSUE TITLE
Last change broke something

### ISSUE THREAD

**Issue by ferronrsmith** [motdotla/dotenv-expand#14]
RPS_SCRIPT=${PEXEC} \\${REMOTE_SERVER_IP} -u ${REMOTE_SERVER_USER} -P ${REMOTE_SERVER_PASSWORD} -i cmd /c ${RPS_SCRIPT_PATH}

`RPS_SCRIPT` does not get resolved. Seems `\\` is affecting dotenv-expand and is preventing interpolation

**Comment by ferronrsmith** [comment]
Tested with dotenv 5, not sure if that's the problem.

**Comment by motdotla** [comment]
Does it resolve partially or not at all?

**Comment by ferronrsmith** [comment]
Not at all. I will write a test and send it when I get to work.

**Comment by ferronrsmith** [comment]
```javascript
    it('should expand windows network path environment variables', function (done) {
      var dotenv = {
        parsed: {
          'EXEC': 'node',
          'MACHINE': '127.0.0.1',
          'REMOTE_CALL': '${EXEC} \\${MACHINE}'
        }
      }
      var obj = dotenvExpand(dotenv).parsed

      obj['REMOTE_CALL'].should.eql('node \\127.0.0.1')
      done()
    })
```

**Comment by motdotla** [comment]
@ferronrsmith can you give this a latest try with the updated dotenv as well.

**Comment by ferronrsmith** [comment]
👍🏾

**Comment by ferronrsmith** [comment]
Issue still exists. It's fine. Already reverted and locked version to previous released that worked.
