### ISSUE TITLE
How to escape `${}`

### ISSUE THREAD

**Issue by CarlosGines** [motdotla/dotenv-expand#15]
I would like to use a variable that contains literally `${id}`. Is there a way to escape it so that it does not try to expand it?

So if I have in .env `URL=https://devices/${id}/users` when I read URL in code I get `https://devices//users` due to the expansion (and no `id` variable present).

How could I get literally `https://devices/${id}/users` from `URL` using this library?

**Comment by motdotla** [comment]
Yes, you can do that like this example here: https://github.com/motdotla/dotenv-expand/blob/master/test/main.js#L82
