### ISSUE TITLE
Env var set to empty in shell does not override existing vars

### ISSUE THREAD

**Issue by geritol** [motdotla/dotenv-expand#18]
I have encountered this issue using creates react app, and have been pointed here.
More info on the issue https://github.com/facebook/create-react-app/issues/5833

**Comment by ericrallen** [comment]
I've noticed this, too, while trying to add `dotenv-expand` to a project. Haven't had a chance to look at the source and see what might be causing it yet.

**Comment by smesgr** [comment]
The same issue was solved in dotenv in version 5.0.0. Would be nice if dotenv-expand would follow.

**Comment by motdotla** [comment]
5.0.0 dotenv-expand now also solves this issue. Thanks for your patience everyone. My delay.
