### ISSUE TITLE
It is not working for angle bracket substition

### ISSUE THREAD

**Issue by xianlin** [motdotla/dotenv-expand#2]
I tried your code but it is not working

```
MONGOLAB_URI=mongodb://${MONGOLAB_USER}:${MONGOLAB_PASSWORD}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}
```

still shows

```
MONGOLAB_URI=mongodb://${MONGOLAB_USER}:${MONGOLAB_PASSWORD}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}
```

ONLY `BASIC_EXPAND=$BASIC` can be converted.

**Comment by Webysther** [comment]
For motdotla/dotenv/pull/97 he said it works, but not.

**Comment by Webysther** [comment]
The PR motdotla/dotenv-expand/pull/3 fix greatly!

**Comment by motdotla** [comment]
You can now use `4.0.x` to get this capability. https://github.com/motdotla/dotenv-expand/pull/5
