### ISSUE TITLE
Preload dotenv-expand

### ISSUE THREAD

**Issue by faustAbc** [motdotla/dotenv-expand#28]
Is it possible to preload ```dotenv-expand``` like dotenv does it?
```
$ node -r dotenv/config your_script.js
```

**Comment by khuongduybui** [comment]
In the mean time, I created https://github.com/khuongduybui/dotenv-with-expand

**Comment by ctsstc** [comment]
Came here looking for this, wish this was an option.

**Comment by motdotla** [comment]
This has actually been worked here: https://github.com/motdotla/dotenv-expand/pull/31/ and should go out by end of the week.

**Comment by motdotla** [comment]
Released 🎉: https://github.com/motdotla/dotenv-expand/blob/master/CHANGELOG.md#800-2022-02-03
