### ISSUE TITLE
Incorrectly expands `$` instead of `${}`

### ISSUE THREAD

**Issue by bre7** [motdotla/dotenv-expand#45]
Package tries to erroneously expand any `$` while it should only expand variables `${}`

Input:
```env
DATABASE_URL="postgres://user:password@server.host:5432/database?ssl=1&schema=schema$1234"
```

Expected:
> DATABASE_URL => postgres://user:password@server.host:5432/database?ssl=1&schema=schema$1234

Actual result:
> DATABASE_URL => postgres://user:password@server.host:5432/database?ssl=1&schema=schema

Fix: https://github.com/prisma/prisma/blob/acbd91a6c517d08f4850b4d2f6794d3773710a29/src/packages/sdk/src/dotenvExpand.ts

**Comment by mattcarlotta** [comment]
The `$` should be escaped when it doesn't refer to an interpolated value:

Input:
```dosini
DATABASE_URL="postgres://user:password@server.host:5432/database?ssl=1&schema=schema\$1234"
```

Output:
```dosini
DATABASE_URL="postgres://user:password@server.host:5432/database?ssl=1&schema=schema$1234"
```

**Comment by nVitius** [comment]
The package tries to expand both `${var_name}` and `$var_name`

You can check out the `test/.env` file for some more examples of what it can do.

Would probably be a good idea to add a short section on syntax in the README

**Comment by motdotla** [comment]
> Would probably be a good idea to add a short section on syntax in the README

Good idea. We'll try to get to this soon.

**Comment by motdotla** [comment]
https://github.com/motdotla/dotenv-expand#what-rules-does-the-expansion-engine-follow

**Comment by rellafella** [comment]
> The `$` should be escaped when it doesn't refer to an interpolated value:

This isn't possible if the `$` is present in a license key, escaping it would ultimately invalidate the key.
