### ISSUE TITLE
fs.readFileSync is not a function

### ISSUE THREAD

**Issue by ayoubgm** [motdotla/dotenv-expand#52]
i get an error about fs.readFileSync  is not a function while import the two packages specified in the doc !
Anyone have the same issue !

`import dotenv from "dotenv";`
`import dotenvExpand from "dotenv-expand";`

`const env = dotenv.config();`
`dotenvExpand(env);`

**Comment by motdotla** [comment]
What version of node are you on @ayoubgm ?
