### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by moselhy** [motdotla/dotenv-expand#65]
A simple `.env` file containing:

SERVER_HOST=localhost:8080
CORS_ALLOWED_ORIGINS=/${SERVER_HOST}(:[0-9]+)?$/

will throw this error when configured:
`TypeError: Cannot read property 'split' of undefined`

This issue wasn't happening in version `5.1.0` but I noticed it in `8.0.1`

**Comment by motdotla** [comment]
You just need to escape the ending $ sign:

```
SERVER_HOST=localhost:8080
CORS_ALLOWED_ORIGINS=/${SERVER_HOST}(:[0-9]+)?\$/
```

Otherwise dotenv-expand attempts to interpolate it.

You raise a good issue though that ideally it should be smart enough to recognize a dollar sign followed by some text as a variable, and dollar signs on their own could exist on their own without being escaped. This would need to be modified in the regex.

I'll look into that, but for now you can just modify your .env file.

**Comment by MattIPv4** [comment]
👋 Just wanted to +1 this as we've also just run into this after updating Next.js, which bumped from 5.x to 8.x for this lib and introduced this bug.

**Comment by felipeespitalher** [comment]
I'm using [serverless-dotenv-plugin](https://github.com/neverendingqs/serverless-dotenv-plugin) and few of my env vars have "$".

I solved escaping all `$`

Ex:

KEY=VAL\\$UE

**Comment by DollarAkshay** [comment]
Had to change some of my passwords that had `$` in them because of this. LOL

**Comment by gabriel-hahn** [comment]
In version `10.0.0`, having a `$` is no longer a problem, but it seems that having `$$` in `.env` values can break it again. I just ran into this when upgrading NextJS: `@next/env` upgrade, which also upgraded this package from version `5.1.0` to `10.0.0`.

**Example:**
`TOKEN ="abcd$1234"` good 👍🏼 
`TOKEN ="abcd$$1234"` bad 👎🏼

**Comment by motdotla** [comment]
in `v11.0.0` functionality will be this:

* `TOKEN ="abcd$1234"` -> `abcd`
* `TOKEN ="abcd$$1234"` -> `abcd$`

if you need to include the `$` sign escape it. we are considering supporting single quotes as an alternative (so you would not need to escape the dollar sign)
