### ISSUE TITLE
Error when declaring a variable referencing itself: X="$X"

### ISSUE THREAD

**Issue by timspro** [motdotla/dotenv-expand#67]
Apologies if this is a known issue or I've missed something here.

I'm on macOS Monterey 12.2.1, node v17.1.9, and dotenv-expand 8.0.1 and was trying to convert a Bash script to dotenv's format.

I ran into an issue with:
```
DIST="${DIST:-$PWD/dist/lib}"
```

Unfortunately, this doesn't seem to work either:
```
TEMP="${DIST:-$PWD/dist/lib}"
DIST="$TEMP"
```

I was expecting for the variable DIST to be defined to "./dist/lib" if it wasn't already defined.

I was surprised to discover something as simple as `DIST="$DIST"` produces the same error:

"RangeError: Maximum call stack size exceeded" on "dotenv-expand/lib/main.js:7:53"

**Comment by motdotla** [comment]
Unfortunately expansion cannot support self referencing variables. I'll consider a way to support this but because referencing variables is a recursive function it's currently not able to handle this.
