### ISSUE TITLE
Expansion issues

### ISSUE THREAD

**Issue by federicobarera** [motdotla/dotenv-expand#7]
Using your test .env file

var dotenv = require('dotenv')
var dotenvExpand = require('dotenv-expand')
var config = dotenv.config();
dotenvExpand(config);
console.log(process.env.MONGOLAB_URI)

--
mongodb://${MONGOLAB_USER}:${MONGOLAB_PASSWORD}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}

Win 8.1
Node: 6.10.0
dotenv: 2.0.0
dotenv-expand: 4.0.1

**Comment by federicobarera** [comment]
config.parsed seems undefined. config already contains all the configuration

**Comment by motdotla** [comment]
@federicobarera I'm going ahead and closing this. Let me know if this is still an issue.
