### ISSUE TITLE
Bracket notation with default does not work with /

### ISSUE THREAD

**Issue by timspro** [motdotla/dotenv-expand#70]
For example:

```
DIST=${APP:-/dist}
```

Currently, DIST will evaluate to "/dist}" instead of the expected "/dist".

Since there is just a one character difference, this could be a pretty easily missed error. Perhaps this notation should be discouraged?

Not using the bracket notation works fine:
```
DIST=$APP:-/dist
```

**Comment by MorisR** [comment]
I'm facing the same issue,

example
![image](https://user-images.githubusercontent.com/10247681/159154003-3cad4c66-9269-4382-978d-f58bf5304721.png)
becomes
![image](https://user-images.githubusercontent.com/10247681/159154007-7a98ce6d-cb8b-4de3-a903-70ba7f570824.png)
