### ISSUE TITLE
default value not working if value includes colon (or other special chars)

### ISSUE THREAD

**Issue by FezVrasta** [motdotla/dotenv-expand#73]
The following configuration:

```js
const dotenv = {
  parsed: {
    BASIC: 'basic',
    BASIC_EXPAND: '${BASIC:-foo:bar}',
    MISSING_EXPAND: '${MISSING:-foo:bar}',
  }
};

console.log(dotenvExpand.expand(dotenv));
```

Results in:

```js
{
  parsed: {
    BASIC: "basic",
    BASIC_EXPAND: "basic:bar}",
    MISSING_EXPAND: "foo:bar}"
  }
} 
```

As you can see there's a problem where $BASIC is defined and its default value includes a colon in it.

Escaping the colon with `\:` doesn't have any effect.

**Comment by FezVrasta** [comment]
I'm trying to fix the bug but I have a question, is this example correct?

https://github.com/motdotla/dotenv-expand/blob/master/tests/.env#L13

Isn't it missing a `:-` between `UNDEFINED_ENV_KEY_2` and `${UNDEFINED_ENV_KEY_3:-default}`?

**Comment by motdotla** [comment]
Thank you!
