### ISSUE TITLE
Allow disabling `$xxx` expansion

### ISSUE THREAD

**Issue by gustavotoyota** [motdotla/dotenv-expand#83]
This feature would be very useful for me.

In CapRover the environment variables don't need a \ to mark dollar signs that aren't expansions, so whenever I have to move environment variables from CapRover to local I need to find all $ and add a \ before them, which is annoying and error-prone.

Also, this would allow variable expansion to be aligned with the usage of backticks in Javascript:
```
const MY_VAR = 123;

console.log(`hello$world`); // hello$world
console.log(`hello${MY_VAR}world`); // hello123world
console.log(`hello\${MY_VAR}world`); // hello${MY_VAR}world
```
While if I try the same in dotenv-expand:
```
MY_VAR=123

TEST1=hello$world # hello
TEST2=hello${MY_VAR}world # hello123world
TEST3=hello\${MY_VAR}world # hello${MY_VAR}world
```

**Comment by scalp42** [comment]
@motdotla I see the same behavior, it prevents you from having any secret with a `$`.

**Comment by motdotla** [comment]
moving conversation here: https://github.com/motdotla/dotenv-expand/issues/101

it's an important one that we will get fixed up correctly and elegantly
