### ISSUE TITLE
Variables names bug

### ISSUE THREAD

**Issue by PatrykKuniczak** [motdotla/dotenv-expand#92]
I have a bug when i create .env file like this:

```
DB=mydb
DB_HOST=localhost
DB_URL=postgres://postgres:myPass@$DB_HOST:5432/$DB
```

i have a output, like this:

```
postgres://postgres:myPass@mydb_HOST:5432/mydb
```

expand see "DB" case and use it in all places where start is "DB", when i change this to "DB_SOMETHING" that's working good, that's issue with regex IMO.

**Comment by FezVrasta** [comment]
I think you want to escape the `$` sign if you don't want it to be expanded. Use `\$` instead.

**Comment by motdotla** [comment]
yes, escape the dollar sign. thank you @FezVrasta
