### ISSUE TITLE
Document breaking changes of v10

### ISSUE THREAD

**Issue by medikoo** [motdotla/dotenv-expand#96]
Changelog just mentions that "Support special characters in default expansion" was added, which doesn't look as breaking change.

If there were breaking changes. Ideally if there's a BREAKING CHANGES section explaining what's breaking exactly

**Comment by motdotla** [comment]
i can understand the frustration since some projects will mention breaking changes but for this project any major upgrade is considered a breaking change.

**Comment by medikoo** [comment]
> major upgrade is considered a breaking change.

What is the problem in stating that in the changelog? At least that would definitely make life easier for us

**Comment by motdotla** [comment]
i'll start to try and do that. thanks @medikoo for the suggestion.
